# Copyright (C) Denys Valchuk - All Rights Reserved
# ZHZhbGNodWtAZ21haWwuY29tCg==
name: Unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  cpp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cpp
    steps:
      - uses: actions/checkout@v4

      - name: Install conan and cmake
        run: |
          pip3 install -q --user conan==2.* cmake==3.23.*
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: find common problems -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run --Werror

      - name: Detect default conan profile if not exists
        run: '[ -f "$HOME/.conan2/profiles/default" ] || conan profile detect'

      - name: Install dependencies
        run: conan install . --build=missing

      - name: Configure project
        run: cmake --preset conan-release

      - name: Build project
        run: cmake --build --preset conan-release

      - name: Run tests
        run: ctest --preset conan-release --output-on-failure

  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test

  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip3 install pytest ruff

      - name: Run tests
        run: python3 -m pytest

      - name: Lint
        run: ruff check .
